// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	health "kubeai-model-manager/internal/handler/health"
	model "kubeai-model-manager/internal/handler/model"
	"kubeai-model-manager/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: health.MetricsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: health.ReadyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/models"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MetricsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/models",
					Handler: model.CreateModelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/models",
					Handler: model.ListModelsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/models/:name",
					Handler: model.GetModelHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/models/:name",
					Handler: model.UpdateModelHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/models/:name",
					Handler: model.DeleteModelHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/models/:name/versions",
					Handler: model.CreateVersionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/models/:name/versions",
					Handler: model.ListVersionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/models/:name/versions/:version",
					Handler: model.GetVersionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/models/:name/versions/:version",
					Handler: model.DeleteVersionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/models/:name/versions/:version/download",
					Handler: model.DownloadVersionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/models/:name/versions/:version/metadata",
					Handler: model.GetMetadataHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/models/register",
					Handler: model.RegisterModelHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/models/version/status",
					Handler: model.UpdateVersionStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
