// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonReq struct {
	Name      string `path:"name"`
	Version   string `path:"version"`
	Presigned bool   `form:"presigned,default=false"`
}

type CommonResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,optional"`
}

type CreateModelReq struct {
	Name        string `form:"name"`
	Description string `form:"description,optional"`
	Framework   string `form:"framework,optional"`
	TaskType    string `form:"task_type,optional"`
	Labels      string `form:"labels,optional"`
	Owner       string `form:"owner,optional"`
}

type CreateVersionReq struct {
	Name             string `form:"name"`
	Version          string `form:"version"`
	Description      string `form:"description,optional"`
	Framework        string `form:"framework,optional"`
	FrameworkVersion string `form:"framework_version,optional"`
	Metrics          string `form:"metrics,optional"`
	Parameters       string `form:"parameters,optional"`
}

type DownloadResp struct {
	StoragePath string `json:"storage_path"`
}

type Model struct {
	ID          uint           `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description,optional"`
	Framework   string         `json:"framework,optional"`
	TaskType    string         `json:"task_type,optional"`
	Owner       string         `json:"owner,optional"`
	Labels      string         `json:"labels,optional"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	Versions    []ModelVersion `json:"versions,optional"`
}

type ModelListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"page_size,default=20"`
	Framework string `form:"framework,optional"`
	TaskType  string `form:"task_type,optional"`
}

type ModelListResp struct {
	Items    []Model `json:"items"`
	Total    int64   `json:"total"`
	Page     int     `json:"page"`
	PageSize int     `json:"page_size"`
}

type ModelMetadataResp struct {
	ModelName    string `json:"model_name"`
	ModelVersion string `json:"model_version"`
	Framework    string `json:"framework"`
	StoragePath  string `json:"storage_path"`
}

type ModelVersion struct {
	ID           uint   `json:"id"`
	ModelID      uint   `json:"model_id"`
	Version      string `json:"version"`
	Description  string `json:"description,optional"`
	StoragePath  string `json:"storage_path"`
	Framework    string `json:"framework,optional"`
	FrameworkVer string `json:"framework_version,optional"`
	Metrics      string `json:"metrics,optional"`
	Parameters   string `json:"parameters,optional"`
	Size         int64  `json:"size"`
	Checksum     string `json:"checksum"`
	Status       string `json:"status"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type ModelVersionListResp struct {
	Items []ModelVersion `json:"items"`
}

type UpdateModelReq struct {
	Name        string `form:"name"`
	Description string `form:"description,optional"`
	Labels      string `form:"labels,optional"`
}

type UpdateVersionStatusReq struct {
	Name     string `form:"name"`
	Version  string `form:"version"`
	Status   string `form:"status"`
	Message  string `form:"message,optional"`
	Instance string `form:"instance,optional"`
	Node     string `form:"node,optional"`
}
