apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: kubeai-jaeger
  namespace: monitoring
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: info
      memory.max-traces: 10000
  storage:
    type: memory
  ingress:
    enabled: true
    hosts:
      - jaeger.kubeai.local