// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	health "kubeai-job-scheduler/internal/handler/health"
	job_scheduler "kubeai-job-scheduler/internal/handler/job_scheduler"
	"kubeai-job-scheduler/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: health.MetricsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: health.ReadyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/jobs"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MetricsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/inference/tasks",
					Handler: job_scheduler.SubmitInferenceTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/inference/tasks/:task_id",
					Handler: job_scheduler.GetInferenceTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tasks/list",
					Handler: job_scheduler.ListTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/training/tasks",
					Handler: job_scheduler.SubmitTrainingTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/training/tasks/:task_id",
					Handler: job_scheduler.GetTrainingTaskHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/jobs"),
	)
}
