// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	health "kubeai-inference-gateway/internal/handler/health"
	inference "kubeai-inference-gateway/internal/handler/inference"
	"kubeai-inference-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: health.MetricsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: health.ReadyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/inference"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MetricsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/control/tasks/:task_id/cancel",
					Handler: inference.CancelTrainingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/control/tasks/:task_id/pause",
					Handler: inference.PauseTrainingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/control/tasks/:task_id/resume",
					Handler: inference.ResumeTrainingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/control/tasks/:task_id/retry",
					Handler: inference.RetryTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/execute",
					Handler: inference.InferenceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/inference"),
	)
}
