// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,optional"`
}

type GetInferenceTaskReq struct {
	TaskID string `json:"task_id"`
}

type GetTrainingTaskReq struct {
	TaskID string `json:"task_id"`
}

type InferenceTask struct {
	TaskID        string                 `json:"task_id"`
	ModelName     string                 `json:"model_name"`
	ModelVersion  string                 `json:"model_version"`
	Resources     ResourceRequest        `json:"resources"`
	InputData     map[string]interface{} `json:"input_data"`
	OutputTopic   string                 `json:"output_topic,optional"`
	Status        string                 `json:"status"`
	Priority      int                    `json:"priority"`
	RetryCount    int                    `json:"retry_count"`
	MaxRetries    int                    `json:"max_retries"`
	CreateTime    string                 `json:"create_time"`
	UpdateTime    string                 `json:"update_time"`
	ScheduledNode string                 `json:"scheduled_node,optional"`
	PodName       string                 `json:"pod_name,optional"`
	ErrorMessage  string                 `json:"error_message,optional"`
}

type InferenceTaskResp struct {
	TaskID  string `json:"task_id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type ListTasksReq struct {
	TaskType string `form:"task_type,options=inference|training"` // 推理或训练
	Status   string `form:"status,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
}

type ListTasksResp struct {
	Items    []interface{} `json:"items"` // InferenceTask 或 TrainingTask
	Total    int64         `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
}

type ResourceRequest struct {
	CPU    string `json:"cpu,optional"`
	Memory string `json:"memory,optional"`
	GPU    string `json:"gpu,optional"`
}

type SubmitInferenceReq struct {
	ModelName    string                 `json:"model_name"`
	ModelVersion string                 `json:"model_version"`
	Resources    ResourceRequest        `json:"resources"`
	InputData    map[string]interface{} `json:"input_data"`
	OutputTopic  string                 `json:"output_topic,optional"`
	Priority     int                    `json:"priority"`
	MaxRetries   int                    `json:"max_retries"`
}

type SubmitTrainingReq struct {
	Name        string          `json:"name"`
	ModelName   string          `json:"model_name,optional"`
	Framework   string          `json:"framework"`
	Command     []string        `json:"command"`
	Args        []string        `json:"args"`
	Resources   ResourceRequest `json:"resources"`
	DatasetPath string          `json:"dataset_path,optional"`
	OutputPath  string          `json:"output_path,optional"`
	Priority    int             `json:"priority"`
	MaxRetries  int             `json:"max_retries"`
}

type TaskControlReq struct {
	TaskID   string `json:"task_id"`
	TaskType string `json:"task_type"` // inference/training
}

type TrainingTask struct {
	TaskID       string          `json:"task_id"`
	Name         string          `json:"name"`
	ModelName    string          `json:"model_name,optional"`
	Framework    string          `json:"framework"`
	Command      []string        `json:"command"`
	Args         []string        `json:"args"`
	Resources    ResourceRequest `json:"resources"`
	DatasetPath  string          `json:"dataset_path,optional"`
	OutputPath   string          `json:"output_path,optional"`
	Status       string          `json:"status"`
	Priority     int             `json:"priority"`
	RetryCount   int             `json:"retry_count"`
	MaxRetries   int             `json:"max_retries"`
	CreatedAt    string          `json:"created_at"`
	UpdatedAt    string          `json:"updated_at"`
	PodName      string          `json:"pod_name,optional"`
	ErrorMessage string          `json:"error_message,optional"`
}

type TrainingTaskResp struct {
	TaskID  string `json:"task_id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type UpdateTrainingTaskReq struct {
	TaskID string `json:"task_id"`
	Status string `json:"status"` // paused/cancelled/resumed
}
