// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,optional"`
}

type ControlReq struct {
	TaskID string `json:"task_id"`
}

type EnvVar struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type InferenceRequest struct {
	Model_name    string                 `json:"model_name"`
	Model_version string                 `json:"model_version,optional"`
	Input         map[string]interface{} `json:"input"`
}

type InferenceResponse struct {
	TaskID string                 `json:"task_id"`
	Result map[string]interface{} `json:"result"`
}

type ResourceRequest struct {
	CPU    string `json:"cpu,optional"`
	Memory string `json:"memory,optional"`
	GPU    string `json:"gpu,optional"`
}

type TrainingTaskReq struct {
	Name        string          `json:"name"`
	ModelName   string          `json:"model_name"`
	Framework   string          `json:"framework"`
	Image       string          `json:"image"`
	Command     string          `json:"command"`
	Args        []string        `json:"args"`
	Resources   ResourceRequest `json:"resources"`
	Distributed bool            `json:"distributed,optional"`
	WorkerNum   int32           `json:"worker_num,optional"`
	Env         []EnvVar        `json:"env,optional"`
	Priority    int             `json:"priority,default=5"`
}

type TrainingTaskResp struct {
	TaskID  string `json:"task_id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}
